### ISSUE TITLE
Proposer's behavior

### ISSUE THREAD

**Issue by slavasn** [fairlayer/fair#12]
Hi guys

You have a very promising project. I'm also working on something right now and try to get involved in reading other peoples code, especially new projects. Consensus is hard, so any opportunity of improving understanding is priceless.

I'm mainly a Java developer, so I apologize if I say some bullshit here) 

I looked through the code and can admit it is an interesting idea - replacing PBFT view changes with just time rounds. It makes it more similar to DPOS actually, without sacrificing finality. If I understood it correctly of course.

Regarding the code, I've got a couple of minor question:
1. Is there a control of how many proposals can active validator do in it's round? And how many prevotes/precommits can other validators do in the same round for the same height? I was not able to find such a check, but it might be because of my poor JavaScript skills. I the case these check are absent, I would suggest to add them as otherwise it is possible to lock the majority of validators on different blocks.

2.  In process_block.js, line 114 `if (!result.success) l(result)` , shouldn't it be `if (!result.success) l(result); return;` as it looks like we are accepting block with partially incorrect  transactions.

Thank you, again, very interesting project. I should find more time and read how is the planned performance will be achieved and probably steal some ideas from you)

**Comment by homakov** [comment]
1. according to `external_rpc/propose` each validator will save whatever valid block comes in 

```
  me.proposed_block = {
    proposer: pubkey,
    sig: sig,

    header: bin(header),
    ordered_tx_body: ordered_tx_body
  }
```

It also checks that the request was send by current validator. An active validator can send as many proposals as they want, but after propose step each validator will have only one proposal that cannot be replaced.

Other validators can prevote just once and everyone else only accepts signatures on the proposal they currently hold. I.e. if all have different proposals no block can be built.

2. there are no invalid tx right now. I.e. validators just sell space in the block, they don't care if you put random bytes in your batch. Same as in EVM, if tx fails, it fails deterministically on all other machines too.

Proper tx validation is pretty expensive so all validators do is ensure you have enough onchain balance to pay for the space, nothing else.

Always ready to give comments or showcase it!

**Comment by slavasn** [comment]
Ahh, I see! Validators can't vote more than once.

Can we assume situation is possible when honest validators are blocked during their rounds (DDOS) and when its again round of A, A sends new blocks to new validators?

 round A:
    A proposes block 1 to B, C

B, C precommit on 1

B, C locked on 1

B - ddos-ed
C - ddos-ed
D - ddos-ed

A - proposes block 2 to C, D

D precommits on 2
D locked on 2

**Comment by homakov** [comment]
D precommits on 2 only after they see 3 prevotes on block 2, and since both B C are already precommited to 1, they will not send prevote for block 2. C will reject proposal of 2 because they already have next height.

We can assume A offered block 2 before block 1 to B C, and somehow stored their prevotes on 2 until now.  Then A could give C's prevote to D (connection A to D is authenticated so it must look like C is connecting to D)

I guess that's what rounds were useful for - D could look at the round and see that this prevote on 2 is round 1 not round 5 as expected...

Maybe, this can be replaced with timestamps on every vote and only accepting ts in safe ranges. That would guarantee that this prevote is "fresh".
