### ISSUE TITLE
shepherd.js usage

### ISSUE THREAD

**Issue by rwwagner90** [fairlayer/fair#21]
👋 Hello! I see you are using shepherd.js in this project. We are so pleased to see that! We would love to showcase your usage in the Shepherd docs, and we would love to hear how things have been going for you using it. What has worked well, do you have any feature requests or improvements, etc. Please let us know!

**Comment by rwwagner90** [comment]
@homakov why was this closed?

**Comment by homakov** [comment]
@rwwagner90 1) because spamming in issues is not ok, there are other ways to contact. 2)  shepherd lib is in repo doesn't mean it's being used

**Comment by rwwagner90** [comment]
@homakov It's not spam. It's legitimate outreach to repos using Shepherd, in an attempt to connect and showcase their work.
